# Usage: Follow the steps in $PWD/README.md.

workspace:
    build: workspace

master:
    build: master
    volumes_from:
        - workspace
    ports:
        - "8010:8010"
    command: ./run.sh -cr
    restart: on-failure

# Use the zera service as template for invoking multiple buildslave containers.
zera:
    build: slaves/latest
    volumes_from:
        - workspace
    links:
        - master:buildmaster
    restart: on-failure
