# Usage: Follow the steps in $PWD/README.md.

workspace:
    build: workspace

master:
    build: master
    volumes_from:
        - workspace
    ports:
        - "8010:8010"
    environment:
        - WORKSPACE_CONFIGURED=false # the run.sh script modifies this to
                                     # signals the builders to start running.
    command: ./run.sh -cr
    restart: on-failure

# Use the zera service as template for invoking multiple buildslave containers.
zera:
    build: slaves/latest
    volumes_from:
        - workspace
    links:
        - master:buildmaster
    command: ./run.sh
    restart: on-failure
