# Usage: Follow the steps in the README file in the directory containing this file

dev:
    extends:
        file: common.yml
        service: workspace
    volumes:
        - $ATOMSPACE_SOURCE_DIR:/atomspace
        - $COGUTILS_SOURCE_DIR:/cogutils
        - $MOSES_SOURCE_DIR:/moses
    working_dir: /opencog # This is the same as the volume mount point below
    links:
        - postgres:db
        - relex:relex
    environment:
        - PGHOST=db # This should be the same as the link's alias
        - PGUSER=opencog_user # user created by configure-database.sh

postgres:
    image: opencog/postgres

relex:
    extends:
        file: relex.yml
        service: relex
    command: /bin/sh -c "ant clean && ant  && ./opencog-server.sh"
