# Follow the instruction below for easy setup of environment
#
# Usage: Follow the steps in the README file in the directory containing this file

dev:
    image: opencog/opencog-dev:cli
    ports: # syntax is host:container
        - "5000:5000"
        - "17001:17001"
        - "18001:18001"
        - "8080:8080"
    working_dir: /opencog # This is the same as the volume mount point below
    volumes:
        - $OPENCOG_SOURCE_DIR:/opencog
        - $HOME/.gitconfig:/home/opencog/.gitconfig
    links:
        - postgres:db
        - relex:relex
    environment: # Set environment variables within the container
        - PYTHONPATH=/usr/local/share/opencog/python
        - OPENCOG_SOURCE_DIR=/opencog
        - PGHOST=db # This should be the same as the link's alias
        - PGUSER=opencog_user # user created by configure-database.sh

postgres:
    image: postgres:latest
    volumes: # for persisting data across sessions
        - $PWD/data/:/var/lib/postgresql/data

relex:
    image: opencog/relex
    ports:
        - "4444:4444"
        - "9000:9000"
        - "3333:3333"
    working_dir: /relex
    volumes:
        - $RELEX_SOURCE_DIR:/relex
    command: /bin/sh -c "ant clean && ant  && ./opencog-server.sh"
