name: build-and-push

on: push

jobs:
  opencog:
    name: opencog-images
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: opencog
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v1

      - name: Login to docker hub
        run: >
          docker login
            -u ${{ github.repository_owner }}
            --password-stdin ${{ secrets.DOCKER_TOKEN }}

      - name: Pull opencog/opencog-deps
        run: docker pull opencog/opencog-deps

      - name: Build opencog/cogutil
        run: ./docker-build.sh -c
      - name: Push opencog/cogutil
        run: >
          docker tag
            opencog/cogutil ${{ env.GITHUB_REPOSITORY_OWNER }}/cogutil
