name: build-and-push

on: push

jobs:
  opencog:
    name: opencog-images
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: opencog
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v1

      - name: Pull opencog/opencog-deps
        run: docker pull opencog/opencog-deps

      - name: Build and push ${{ github.repository_owner }}/cogutil
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: opencog/cogutil
          path: cogutil
