name: build-and-push

on: push

jobs:
  opencog:
    name: opencog-images
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2

      - name: Build and push opencog-deps image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_REPOSITORY_OWNER }}/opencog-deps
          tags: latest
          path: opencog/base

      - name: Build and push cogutil image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: ${{ secrets.DOCKER_REPOSITORY_OWNER }}/cogutil
          tags: latest
          path: opencog/cogutil
